kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: gradle:8-jdk17
    volumes:
      - name: gradle-cache
        path: /home/gradle/.gradle
    commands:
      - pwd
      - ./gradle assemble
      - ./gradle check

#  - name: docker publish
#    image: plugins/docker
#    settings:
#      repo: sledy/test-app
#      tags: latest
#      registry: DockerRegistry:5000
#      auto_tag: true
#      when:
#        branch:
#          - main

volumes:
  - name: gradle-cache
    temp: {}
