kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: gradle:8-jdk17  # Match your Gradle and JDK version
    volumes:
      - name: gradle-cache
        path: /home/gradle/.gradle
    commands:
      - ./gradlew clean bootBuildImage --no-daemon

  - name: docker publish
    image: plugins/docker
    settings:
      repo: your-username/your-app
      tags: latest
      registry: DockerRegistry:5000
      auto_tag: true
      when:
        branch:
          - main

volumes:
  - name: gradle-cache
    temp: {}
