name: Test Docker Container Detached

on:
  workflow_dispatch:

jobs:
  run-container:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: docker pull alpine:latest

      - name: Run container in detached mode
        run: docker run -d --name test-alpine alpine:latest tail -f /dev/null
