name: Test Docker Container

on:
  workflow_dispatch: # allows manual trigger

jobs:
  run-container:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: docker pull alpine:latest

      - name: Run container
        run: docker run --rm alpine:latest echo "Hello from inside the container"
